name: Publish Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: x86_64
          # platforms: aarch64,x86_64

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip setuptools
          pip install cibuildwheel twine

      - name: Build wheels with cibuildwheel
        env:
          CIBW_SKIP: "cp36-* *_i686 *-musllinux_* pp*-manylinux_aarch64"
          # CIBW_ARCHS: "aarch64 x86_64"
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/htoik/fourier-mellin/manylinux_x86_64:latest
          CIBW_MANYLINUX_AARCH64_IMAGE: "" # ghcr.io/htoik/fourier-mellin/manylinux_aarch64:latest
          CIBW_MANYLINUX_I686_IMAGE: ""
          CIBW_MANYLINUX_PYPY_I686_IMAGE: ""
          CIBW_MANYLINUX_PPC64LE_IMAGE: ""
          CIBW_MANYLINUX_S390X_IMAGE: ""
          CIBW_MANYLINUX_ARMV7L_IMAGE: ""
          CIBW_MUSLLINUX_X86_64_IMAGE: ""
          CIBW_MUSLLINUX_AARCH64_IMAGE: ""
          CIBW_MUSLLINUX_I686_IMAGE: ""
          CIBW_MUSLLINUX_PPC64LE_IMAGE: ""
          CIBW_MUSLLINUX_S390X_IMAGE: ""
          CIBW_MUSLLINUX_ARMV7L_IMAGE: ""
          # # Temp fix for cmake fetchcontent in aarch64
          # CIBW_BEFORE_BUILD: |
          #   if [ "$CIBW_ARCH" = "aarch64" ]; then
          #     yum install -y git;
          #   fi
        run: python -m cibuildwheel --output-dir wheelhouse .

      - name: Build source distribution
        run: python setup.py sdist --dist-dir wheelhouse

      - name: List generated wheels
        run: ls -la wheelhouse

      - name: Publish package to PyPI
        run: twine upload --skip-existing wheelhouse/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
